# This CI Configuration is responsible for creating an up-to-date XeTeX container, and compiling my resume.

variables:
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

stages:
  - build
  - release
  - compile

build_job:
  stage: build
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE
  only:
    - docker

release_job:
  stage: release
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - docker

compile_job:
  stage: compile
  image: registry.gitlab.com/zackhorvath/resume:latest
  script:
    - xelatex resume_cv.tex
    - git config --global user.email "$GITLAB_USER_EMAIL"
    - git config --global user.name "GitLab CI"
    - git add resume_cv.pdf
    - git commit -m "Committing Updated Resume to Repo [skip ci]"
    - git push https://zackhorvath:${GITLAB_ACCESS_TOKEN}@gitlab.com/zackhorvath/resume.git HEAD:$CI_COMMIT_REF_SLUG
  artifacts:
    paths:
      - "*.pdf"
  only:
    - master
