# This CI Configuration is responsible for creating an up-to-date XeTeX container, and compiling my resume.

image: docker:stable

variables:
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

stages:
  - build
  - release
  - compile

build_job:
  stage: build
  services:
    - docker:dind
  script:
    - docker build -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE
  only:
    - docker

release_job:
  stage: release
  services:
    - docker:dind
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - docker

compile_job:
  stage: compile
  image: zackhorvath/resume:latest
  script:
    - xelatex resume_cv.tex
    - git add resume_cv.pdf
    - git commit -m "Resume PDF $CI_COMMIT_REF_SLUG"
    - git push
  artifacts:
    paths:
      - "*.pdf"
  only:
    - master
